"""empty message

Revision ID: 451854d817f5
Revises: 585259c3ba5f
Create Date: 2020-05-10 15:23:49.887980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451854d817f5'
down_revision = '585259c3ba5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    # ### end Alembic commands ###
