"""rename timeseries to measurement

Revision ID: 585259c3ba5f
Revises: f27d9058684c
Create Date: 2020-05-10 13:14:49.965494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '585259c3ba5f'
down_revision = 'f27d9058684c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeseries_timestamp', table_name='timeseries')
    op.drop_table('timeseries')
    op.create_index(op.f('ix_measurement_timestamp'), 'measurement', ['timestamp'], unique=False)
    op.add_column('variable', sa.Column('name', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    op.drop_column('variable', 'name')
    op.drop_index(op.f('ix_measurement_timestamp'), table_name='measurement')
    op.create_table('timeseries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.Column('achive_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variable_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achive_id'], ['achive.id'], name='timeseries_ibfk_1'),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], name='timeseries_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_timeseries_timestamp', 'timeseries', ['timestamp'], unique=False)
    # ### end Alembic commands ###
