"""users table

Revision ID: 6dc59cafadb3
Revises: 3ac300b195ee
Create Date: 2020-02-01 19:03:39.455831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dc59cafadb3'
down_revision = '3ac300b195ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['public_id'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'public_id')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
