"""change in measurement

Revision ID: b00fe3ba0f21
Revises: 451854d817f5
Create Date: 2020-05-10 16:28:16.451877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b00fe3ba0f21'
down_revision = '451854d817f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('time', sa.Float(), nullable=True))
    op.drop_index('ix_measurement_timestamp', table_name='measurement')
    op.drop_column('measurement', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_measurement_timestamp', 'measurement', ['timestamp'], unique=False)
    op.drop_column('measurement', 'time')
    # ### end Alembic commands ###
