"""add name to variable

Revision ID: f05d2a0a4005
Revises: 02cc4e190942
Create Date: 2020-05-09 13:39:13.819711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05d2a0a4005'
down_revision = '02cc4e190942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('name', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_variable_name'), 'variable', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_name'), table_name='variable')
    op.drop_column('variable', 'name')
    # ### end Alembic commands ###
