FROM continuumio/miniconda3:latest


# Create the environment:
COPY environment.yml .
RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# Install Python dependencies
RUN pip install supervisor

WORKDIR /usr/src/workers

# Spawn workers according to config
ENTRYPOINT ["conda", "run", "-n", "myenv", "/bin/bash", "-c", "supervisord -c supervisord.conf -n"]
