version: "2"
services:
  models_server_api:
    image: models_server
    build:
      context: .
      dockerfile: Dockerfile.models_server
    depends_on:
      - redis
    links:
      - db
      - redis
    ports:
      - "5001:5000"
      - "8889:8888"
    environment:
      FLASK_APP: runserver.py
    volumes:
      - ./models_server/models_server:/models_server

  db:
    image: mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: ["sh", "-c", "redis-server --appendonly yes"]

  workers:
    image: workers
    build:
      context: .
      dockerfile: Dockerfile.workers
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./workers:/usr/src/workers
      - ./models_server/models_server:/models_server

  rq-dashboard:
    image: rq-dashboard
    build:
      context: .
      dockerfile: rq-dashboard/Dockerfile
    ports:
      - '9181:9181'
    expose:
      - "9181"
    links:
      - redis
    depends_on:
      - redis

  react:
    image: react
    build:
      context: .
      dockerfile: react/Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
