name: myenv
channels:
  - conda-forge
dependencies:
  - flask
  - pyfmi
  - fmpy
  - pip
  - pip:
    - mysql-connector-python
    - flask_sqlalchemy
    - flask-migrate
    - pyjwt
    - redis
    - rq
